### PR TITLE
Ivanov

### PR DESCRIPTION
**Pull request by Razmalin**
Added Z-1, Q-4

### CODE REVIEW

**Review by NikolaySavenko — APPROVED** [review]
I hope it works

**Review by Nestea-tea13 — APPROVED** [review]
Q-4 good

**Review by NikolaySavenko — CHANGES_REQUESTED** [review]
make class public

**Comment by Nestea-tea13** [comment]
Добавить в классе public

**Review by NikolaySavenko — APPROVED** [review]
OK

**Review by Nestea-tea13 — APPROVED** [review]
All good

**Pull request merged**
